import jsPDF from 'jspdf';
import { BlueprintElement } from './ifcExporter';

export function exportBlueprintPDF(
  elements: BlueprintElement[],
  projectName: string,
  clientName: string,
  date: string
): Blob {
  const doc = new jsPDF('l', 'mm', 'a1');

  doc.setFontSize(24);
  doc.text(projectName, 20, 20);
  doc.setFontSize(12);
  doc.text(`Client: ${clientName}`, 20, 35);
  doc.text(`Date: ${date}`, 20, 45);
  doc.text('Generated by Sovereign Dominion', 20, 55);

  let y = 75;
  doc.setFontSize(16);
  doc.text('Bill of Materials', 20, y);
  y += 10;

  doc.setFontSize(11);
  doc.text('Item', 20, y);
  doc.text('Quantity', 120, y);
  doc.text('Unit', 160, y);
  doc.text('Material', 200, y);
  y += 7;
  doc.line(20, y, 350, y);
  y += 5;

  for (const el of elements) {
    doc.text(el.id, 20, y);
    doc.text(String(el.quantity), 120, y);
    doc.text(el.unit, 160, y);
    doc.text(el.material, 200, y);
    y += 8;
    if (y > 500) {
      doc.addPage();
      y = 20;
    }
  }

  return doc.output('blob');
}
